#!/bin/bash

spaces (){
  hyprctl workspaces -j | jq -Mc 'map({name: .name, icon: (if .name == "Shell" then "" elif .name == "Web" then "" else "󰎔" end), windows: .windows})'
}

spaces
socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
	spaces
done
