[timer]
idle_timeout = 300
short_break_timeout = 5400
long_break_timeout = 10800
short_break_duration = 300
long_break_duration = 600

[notification]
show_progress_bar = true
minimum_update_delay = 1
