[pyprland]
hyprland_version = "0.49.0"
plugins = [
  "magnify",
  "wallpapers"
]

[wallpapers]
path = "~/images/wallpapers/"
interval = 60
extensions = ["jpg", "jpeg", "png"]
recursive = true
command = 'swww img "[file]"'
clear_command = "swww clear"
